# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1d66b24cf0d66f6ccf57d9e949b1c7c8"
name = "Intastellar Consents"
application_url = "https://www.consentsplatform.com/"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_checkout_branding_settings,read_themes"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://consentsplatform.com/api/auth" ]

[webhooks]
api_version = "2026-04"
